# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
cache: packages
sudo: true
dist: trusty

addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

r_packages:
  - rmarkdown
  - covr
  - testthat

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e "capabilities()"
